[project]
name = "code-snippet-manager"

[build]
frontend = "client"
backend = "server"

[env]
MONGODB_URI = "mongodb+srv://your_username:your_password@your_cluster.mongodb.net/your_database"
JWT_SECRET = "your_jwt_secret"

[deploy]
region = "ap-south-1"  # Mumbai region

[frontend]
build = "npm run build"
start = "serve -s build"

[backend]
build = "npm install"
start = "node server.js"

