[project]
name = "code-snippet-manager"

[build]
frontend = "client"
backend = "server"

[env]
MONGODB_URI = "mongodb+srv://mahendrapatel9824039954:${MONGODB_PASSWORD}@jashmin10.lbck83z.mongodb.net/your_database"
JWT_SECRET = "${JWT_SECRET}"
NODE_ENV = "production"

[deploy]
region = "ap-south-1"

[frontend]
build = "npm run build"
start = "serve -s build"

[backend]
build = "npm install && npm run build"
start = "npm start"

